version: '3.8'

services:
  couchdb:
    image: couchdb:3.3
    container_name: couchdb
    volumes:
      - couchdb_data:/opt/couchdb/data
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - couchdb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  couchdb_data: